wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1709868341.573255
    t:
      1:
      - 1
      - 11
      - 12
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 12
      - 49
      - 55
      - 71
      - 105
      3:
      - 2
      - 23
      4: 3.10.13
      5: 0.16.3
      6: 4.38.1
      8:
      - 2
      - 5
      13: linux-x86_64
